[package]
name = "makrust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["cookie"] }
time = "0.3"
tokio = { version = "1.53.1", features = ["full"] }
sqlx = { version = "0.9", features = [ "runtime-tokio", "tls-rustls-ring-webpki", "postgres", "chrono", "uuid", "ipnetwork" ] }
serde = { version = "1.0.151", features = ["derive"] }
chrono = { version = "0.4.45", features = ["serde"] }
config = "0.15.25"
validator = "0.21.0"
argon2 = { version = "0.5.3", features = ["std"] }
postmark = { version = "2.0.1", features = ["reqwest-rustls-tls"] }
dotenv = "0.15.0"
tower-http = { version = "0.7.0", features = ["cors"] }

[dev-dependencies]
axum-test = "21.0.0"
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
serde_json = "1.0.143"
cookie = "0.18"
wiremock = "0.6.5"
