application:
  port: 8000
  host: 0.0.0.0
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "makrust"
auth:
  # How many days a session stays valid for after signing in
  session_ttl_days: 30
